spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useSSL=false&serverTimezone=UTC
    username: root
    password: admin
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  data:
    web:
      pageable:
        size-parameter: size
        page-parameter: page
        default-page-size: 10
        one-indexed-parameters: false
#        max-page-size: 2000
        max-page-size: 20
        prefix:
#        qualifier-delimeter:
#logging:
#  file: error.log
#  level:
#    appbeta:
#      blog:
#        error:
#          ApiExceptionHandler: INFO